### ISSUE TITLE
BOARD_MECREATOR2.h has no pins for E2 

### ISSUE THREAD

**Issue by ellensp** [Geeetech3D/Prusa_I3_3Dprinter#12]
The board has plugs for 3 extruders, but the board pins files has no definitions for E2

**Comment by ellensp** [comment]
Its in the wild now, and people are trying to use it.

**Comment by Geeetech3D** [comment]
We will add it in the next version.

**Comment by Vertabreak** [comment]
should add pins for E2 on all GT2560 boards

**Comment by Vertabreak** [comment]
i took care of this in source.
https://github.com/MarlinFirmware/Marlin/commits?author=Vertabreak
