### ISSUE TITLE
buzzer.h not found (A10M)

### ISSUE THREAD

**Issue by fishcu** [Geeetech3D/Prusa_I3_3Dprinter#14]
I'm trying to build latest commit from this repo for the A10M on Arduino IDE 1.8.5.
I get the following error:
```
sketch/stepper.cpp:57:20: fatal error: Buzzer.h: No such file or directory
 #include "Buzzer.h"
```

Please advise on how to solve this problem.

**Comment by Geeetech3D** [comment]
Check to see if Buzzer.h exists. Arduino recommended version: 1.8.5/1.8.7

**Comment by fishcu** [comment]
It does not exist. I already solved the problem in the pull request I linked.
There is a spelling mistake in the include: it should be lower case "**b**uzzer.h" instead of "**B**uzzer.h".

Please have a look at the pull request and accept it if you think the quality is good:
https://github.com/Geeetech3D/Prusa_I3_3Dprinter/pull/16

Are you familiar with "pull requests"?
